var data = {
    parts:5 ,
    names:[
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
        'Lorem ipsum dolor sit amet.',
    ],
    circles:[
        {
            name:'sloy1',
            qr:[
                [
                    {
                        mark:1,
                        n:7,
                        size:'medium',
                        color:"green",
                    },
                    {
                        mark:1,
                        n:5,
                        size:'small',
                        color:"red",
                    },
                    {
                        mark:2,
                        n:7,
                        size:'medium',
                        color:"yellow",
                    },
                    {
                        mark:2,
                        n:5,
                        size:'big',
                        color:"red",
                        stroke:'stroke',
                    },
                    {
                        mark:1,
                        n:9,
                        size:'medium',
                        color:"red",
                    },
                    {
                        mark:3,
                        n:5,
                        size:'small',
                        color:"green",
                    },
                    {
                        n:7,
                        size:'small',
                        color:"red",
                    },
                    {
                        n:5,
                        size:'small',
                        color:"red",
                        stroke:'stroke',
                    },
                    {
                        mark:3,
                        n:9,
                        size:'medium',
                        stroke:'stroke',
                        color:"green",
                    },
                ],
                [],
                [],
                [
                    {
                        mark:2,
                        n:0,
                        size:'big',
                        color:"red",
                    },
                ],
            ]
        },
        {
            name:'sloy2',
            qr:[
                [
                    {
                        n:10,
                        size:'medium',
                        color:"green",
                    },
                    {
                        n:5,
                        size:'small',
                        color:"yellow",
                    },
                    {
                        mark:2,
                        n:6,
                        size:'small',
                        color:"yellow",
                    },
                    {
                        n:16,
                        size:'big',
                        color:"red",
                    },
                    {
                        mark:2,
                        n:4,
                        size:'big',
                        color:"green",
                    },
                    {
                        n:10,
                        size:'small',
                        color:"green",
                        stroke:'stroke',
                    },
                    {
                        mark:1,
                        n:5,
                        size:'medium',
                        color:"green",
                    },
                    {
                        n:6,
                        size:'medium',
                        color:"red",
                    },
                    {
                        n:16,
                        size:'small',
                        color:"red",
                    },
                    {
                        mark:3,
                        n:4,
                        size:'small',
                        color:"yellow",
                    },
                    
                    {
                        n:16,
                        size:'small',
                        color:"red",
                    },
                    {
                        n:4,
                        size:'small',
                        color:"green",
                    },
                ],
                [
                    {
                        n:9,
                        size:'medium',
                        color:"green",
                    },
                    {
                        mark:3,
                        n:4,
                        size:'medium',
                        stroke:'stroke',
                        color:"red",
                    },
                    {
                        n:3,
                        size:'medium',
                        color:"green",
                    },
                    {
                        n:"23",
                        size:'big',
                        color:"red",
                    },
                ],
                [   {
                        n:"5",
                        size:'big',
                        color:"green",
                    },
                    {
                        n:6,
                        size:'medium',
                        color:"yellow",
                    },
                    {
                        n:7,
                        size:'small',
                        color:"green",
                    },
                    {
                        mark:2,
                        n:8,
                        size:'big',
                        color:"green",
                    },
                ],
                [
                    {
                        n:33,
                        size:'medium',
                        color:"green",
                    },
                    {
                        mark:3,
                        n:4,
                        size:'medium',
                        stroke:'stroke',
                        color:"red",
                    },
                    {
                        mark:3,
                        n:5,
                        size:'big',
                        color:"green",
                    },
                    {
                        n:3,
                        size:'big',
                        color:"green",
                    },
                ],
            ]
        },
        {
            name:'sloy3 ',
            qr:[
                [
                    {
                        mark:2,
                        n:6,
                        size:'medium',
                        stroke:'stroke',
                        color:"green",
                    },
                    {
                        n:5,
                        size:'small',
                        color:"green",
                    }
                ],
                [],
                [],
                [
                    {
                        n:4,
                        size:'small',
                        color:"red",
                    },
                    {
                        mark:3,
                        n:8,
                        size:'small',
                        color:"green",
                    },
                    {
                        n:8,
                        size:'big',
                        color:"red",
                    },
                    {
                        mark:2,
                        n:5,
                        size:'small',
                        color:"green",
                    },
                    {
                        mark:3,
                        n:9,
                        size:'small',
                        color:"green",
                    },
                    {
                        mark:1,
                        n:6,
                        size:'small',
                        color:"red",
                    },
                    
                ],
                [

                ],
                [
                    {
                        n:6,
                        size:'medium',
                        color:"yellow",
                    },
                ],
                [
                    {
                        n:6,
                        size:'medium',
                        color:"red",
                    },
                ]
            ]
        }
    ],
};